### ISSUE TITLE
Strange response time values

### ISSUE THREAD

**Issue by filnet** [magnet/metered-rs#18]
Hi,

I just started using metered and I am seeing results I don't understand.

```
WorldMetrics { response_time: AtomicHdrHistogram { HdrHistogram {
            samples: 1, min: 1080, max: 1087, mean: 1084, stdev: 0,
            90%ile = 1087, 95%ile = 1087, 99%ile = 1087, 99.9%ile = 1087, 99.99%ile = 1087 } } }
```

How come min != max with a single sample ?

**Comment by eliaslevy** [comment]
Min and max are not the lowest or highest values recorded in the histogram.  Rather, they are the lowest value that could be stored in the lowest bucket and the highest value that could be stored in the highest bucket.  They represent the histogram's range.

**Comment by filnet** [comment]
Makes sense. Thanks for the answer.
