### ISSUE TITLE
Is the only way to access metrics via serde?

### ISSUE THREAD

**Issue by nemosupremo** [magnet/metered-rs#25]
Hi,

Maybe I'm not reading the documentation correctly, but I'm trying to access the metrics generatd by the library (to format and print to the console) and it seems the only way to do so is to roundtrip via some serde serializer? I feel like I'm missing something.

**Comment by magnet** [comment]
Hi,

Generated metric registries are regular Rust structs, so you can access the different metrics directly, and do whatever reading or transforms you need.  Metrics implement Serialize to hook various back-ends that require different formats, notably Prometheus which is supported since 0.4.

**Comment by nemosupremo** [comment]
Ok, it sounds like I'm using the library incorrectly? For example, using the library manually I have

```rust
#[derive(Default, Debug)]
pub struct Perf {
    fps: Throughput,
}

fn main() {
    let metrics = Perf::default(); 
    let fps = &metrics.fps;
    loop {
        measure!(fps, expensive())) 
        // println!("{}", fps.mean())
    }
}
```

However, the internal Histogram isn't visible, so I can't call fps.mean()?. Am I supposed to implement my own `Throughput` type?

**Comment by magnet** [comment]
Hmm, that's an oversight, I feel like we should expose the inner histogram.  Would you like to open that PR?
