### ISSUE TITLE
Same Metered Registry with multiple impl block. 

### ISSUE THREAD

**Issue by KaranP16** [magnet/metered-rs#8]
Hey, 
So in my rust project, there is struct called Shard and there multiple impl blocks exists that too in different files. 
So how can I use metered-rs with same registry for this use case?
I tried putting this macro `#[metered(registry = ShardMetricRegistry , registry_expr = self.metric_registry.metric, visibility = pub(self))]
` on multiple impl blocks like this.

file : src/shard.rs
```rust
#[metered(registry = ShardMetricRegistry , registry_expr = self.metric_registry.metric, visibility = pub(self))]
impl Shard {
    #[measure(HitCount)]
    pub fn metered_test(&self) {
        println!("this function do nothing");
    }
}
```
file : src/shard_var.rs
```rust
pub struct Shard {
    pub metric_registry : ShardMetric
}

#[derive(Debug,Default,serde::Serialize)]
pub struct ShardMetric {
    pub metric : ShardMetricRegistry
}

#[metered(registry = ShardMetricRegistry , registry_expr = self.metric_registry.metric, visibility = pub(self))]
impl Shard {
    #[measure(HitCount)]
    #[measure(ErrorCount)]
    #[measure(ResponseTime)]
    pub fn put_data(&self, dara: Data) -> Result<(),()> {
       //doing nothing
      Some(())
    }
}
```
In this case I am getting this compilation error.
"no field `metered_test` on type `shard::shard_var::ShardMetricRegistry`
pub fn metered_test(&self) {
^^^^^^^^^^^^ unknown field"

Error is indicating that metered-rs didn't encounter second impl block from src/shard_var.rs file.
Does metered-rs capable of handling such case? if yes then plz suggest how.
Thanks.

**Comment by magnet** [comment]
Unfortunately, this is a limitation in Rust macros -- each syntactic item is independent, and we cannot know in advance of the existence of another impl block (or read it). Registries are generated at the same time as we process impl blocks.

Something you can do is bundle all your measured methods in the same impl block, and forward them to their implementation in different impl blocks

**Comment by KaranP16** [comment]
Cool. Thanks for such a quick response.

**Comment by magnet** [comment]
You're welcome.  For the record, it is also possible to generate one metric registry per impl block that you encapsulate in your own registry struct.
