### ISSUE TITLE
Add ability to Clear registries

### ISSUE THREAD

**Issue by theli-ua** [magnet/metered-rs#9]
I couldn't find a way to clear a whole registry. 
In fact with proc macro way of measuring I couldn't find a way to clear even a single metric;

Maybe just the documentation is lacking?

**Comment by magnet** [comment]
Hey, seems like I missed to derive `Clear` on registries -- even though individual metrics must implement it. 

It's a pretty straightforward fix in `metered-macro`, would you like to try build the PR?
